advertisingForum/ads/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path("register",views.register,name="register"),
    path("login", views.log, name="log"),
    path("logout",views.logoutuser,name="logout"),
    path("create",views.create,name="create"),
    path("<int:adId>",views.detail,name="detail"),
    path("my",views.my,name="my"),
    path("my/<int:adId>",views.edit,name="edit"),
    path("delete/<int:adId>",views.deleteAd,name="delete"),
    path("search",views.search,name="search"),
    path("industry/<str:industryKey>",views.display_industry,name="display_industry"),
    path("like/<int:adId>",views.like,name="like"),
    
]

advertisingForum/advertisingForum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ads.urls')),
    
]

advertisingForum/ads/models.py
from django.db import models
from django.contrib.auth.models import User

class Advertisement(models.Model):
    company=models.CharField(max_length=300)
    adress = models.CharField(max_length=400)
    email = models.EmailField(max_length=254)
    phone =models.CharField(max_length=14)
    desc=models.TextField()
    industries=[
        #('skrot ktory jest przechowywany w bazie danych',
        # "pelna nazwa widoczna dla uzytkownika")
        ("","Choose industry"),
        ("re","Real estate"),
        ("ht","Health"),
        ("at","Automotive"),
        ("ft","Fitness"),
    ]
    industry = models.CharField(max_length=2,choices=industries, default="")
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    likes=models.ManyToManyField(User,blank=True,related_name="likes")
    
    def __str__(self):
        return self.company

    def display_industry(self):
        for industry in self.industries:
            if self.industry in industry:
                toDisplay = industry[1]
        return toDisplay

    def total_likes(self):
        return self.likes.count()

advertisingForum/ads/forms.py
from django import forms
from .models import Advertisement
class AdForm(forms.ModelForm):
    class Meta:
        model= Advertisement
        #fields = ('company',"address")
        exclude = ("user",)

advertisingForum/ads/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate,login,logout
from .forms import AdForm
from django.contrib.auth.decorators import login_required
from .models import Advertisement
from django.db.models import Q
#auth

def register(request):
    if request.method =="GET":
        return render(request,'register.html',{"form":UserCreationForm()})
    else:#POST
        if request.POST.get("password1")==request.POST.get("password2"):
            try:
                user=User.objects.create_user(username=request.POST.get("username"),password=request.POST.get("password2"))
            except IntegrityError:
                error="This username is already taken.Try using different one."
                return render(request,'register.html',{"form":UserCreationForm(),"error":error})
            else:#wykonuje sie kiedy try nie dojdzie do bledu
                user.save()
                login(request,user)
                return redirect("home")
        else:
            error="Passwords did not match.Try again."
            return render(request,'register.html',{"form":UserCreationForm(),"error":error})
        

def log(request):
    if request.method=="GET":
        return render(request,"log.html",{"form":AuthenticationForm()})
    else:   
        user = authenticate(username=request.POST.get("username"), password=request.POST.get("password"))
        if user is not None:
            login(request,user)
            return redirect("home")
        else:
            error="Username or password is wrong.Try again"
            return render(request,'log.html',{"form":AuthenticationForm(),"error":error})

@login_required()
def logoutuser(request):
    logout(request)
    return redirect("home")
#ads


def home(request):
    ads=Advertisement.objects.all()
    for ad in ads:
        if ad.likes.filter(id=request.user.id).exists():
            ad.is_liked=True
        else:
            ad.is_liked=False

    return render(request,'home.html',{"ads":ads})

def detail(request,adId):
    ad = get_object_or_404(Advertisement,pk=adId)
    if ad.likes.filter(id=request.user.id).exists():
        ad.is_liked=True
    else:
        ad.is_liked=False
    return render(request,"detail.html",{"ad":ad})

@login_required
def my(request):
    ads=Advertisement.objects.filter(user=request.user)
    for ad in ads:
        if ad.likes.filter(id=request.user.id).exists():
            ad.is_liked=True
        else:
            ad.is_liked=False

    return render(request,"my.html",{"ads":ads})

@login_required
def create(request):
    if request.method =="GET":
        return render(request,"create.html",{"form":AdForm(),"ad":Advertisement})
    else:#jesli w if  get to w else post
        form = AdForm(request.POST)
        if form.is_valid():
            ad = form.save(commit=False)
            ad.user = request.user
            ad.save()
            return redirect("home")
        else:
            error="Something went wrong. Try again"
            return render(request,"create.html",{"form":AdForm(),"error":error})

@login_required
def edit(request,adId):
    ad=get_object_or_404(Advertisement,pk=adId,user=request.user) #upewniam sie ze tylko uzytkownik,do ktorego ogloszenie nalezy moze je edytowac
    if request.method =="GET":
        form=AdForm(instance=ad)
        return render(request,"edit.html",{"form":form,"ad":ad})
    else:
        form=AdForm(request.POST,instance=ad)
        if form.is_valid():
            form.save()
            return redirect("my")
        else:
            error="Something went wrong. Try again"
            return render(request,"edit.html",{"form":form,"ad":ad,"error":error})
@login_required
def deleteAd(request,adId):
    ad=get_object_or_404(Advertisement,pk=adId,user=request.user)
    ad.delete()
    return redirect("my")

def search(request):
    keyWords = request.POST.get("search").split(" ")
    for word in keyWords:
        queryset=Advertisement.objects.filter(Q(company__icontains=word) | Q(desc__icontains=word))
        try:
            ads = ads | queryset
        except:
            ads = queryset
    for ad in ads:
        if ad.likes.filter(id=request.user.id).exists():
            ad.is_liked=True
        else:
            ad.is_liked=False

    return render(request,"home.html",{"ads":ads})

def display_industry(request,industryKey):
    ads = Advertisement.objects.filter(industry=industryKey)
    for ad in ads:
        if ad.likes.filter(id=request.user.id).exists():
            ad.is_liked=True
        else:
            ad.is_liked=False

    return render(request,"home.html",{"ads":ads})

@login_required
def like(request,adId):
    ad = get_object_or_404(Advertisement,pk=adId)
    if ad.likes.filter(id=request.user.id).exists():#sprawdzenie czy uzytkownik juz lubi ogloszenie
        ad.likes.remove(request.user)#odlubienie  
    else:
        ad.likes.add(request.user)
    return redirect("detail",adId=ad.id)



    #Ania koduje123

advertisingForum/ads/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;1,200;1,300;1,400&display=swap" rel="stylesheet">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" href="{% static "css/queries.css" %}">
        <title>Ogłoszenia</title>
    </head>

<body>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <ion-icon name="cloud"></ion-icon>
    {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "home" %}">Advertisements</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "create" %}">Create ad</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "my" %}">My ads</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Industries
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href={% url "display_industry" "re" %}>Real estate</a></li>
            <li><a class="dropdown-item" href={% url "display_industry" "ht" %}>Health</a></li>
            <li><a class="dropdown-item" href={% url "display_industry" "at" %}>Automotive</a></li>
            <li><a class="dropdown-item" href={% url "display_industry" "ft" %}>Fitness</a></li>
          </ul>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "logout" %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "register" %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "log" %}">Log in</a>
        </li>
        
        {% endif %} 
      </ul>
      <form class="d-flex" action={% url "search" %} method="POST">
        <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        {% csrf_token %}
      </form>
    </div>
  </div>
</nav>
    

{% block content %}

{% endblock content %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</body>
</html>

advertisingForum/ads/templates/create.html
{% extends 'base.html' %}

{% block content %}
<div class="row"></div>

    <h2 class="form-title">Create Adevrtisement</h2>
    {% if error %}
    <div class="alert alert-danger" role="alert">A simple danger alert—check it out!</div>
    {% endif %}
    <form class="create-form" action="{% url "create" %}" method="POST">
        <div class="form-line">
            <div class="form-element">
                <label for="id company">Company</label>
                
                <input type="text" name="company" maxlength="300" required="" id="id_company">
            </div>
            <div class="form-element">
                <label for="id-industry">industry</label>
                <select name="industry" required="" id="id_industry">
                    {% for id,industry in ad.industries %}
                    {% if id %}
                    <option value="{{id}}">{{industry}}</option>
                    {% else %}
                    <option value="{{id}}"selected disabled>{{industry}}</option>
                    {% endif %}

                    {% endfor %}

                </select>
            </div>
        </div>
        <div class="form-line">
            <div class="form-element long">
                <label for="id_address">Address</label>
                <input type="text" name="adress" maxlength="400" required="" id="id_adress">
            </div>
        </div>
        <div class="form-line">
            <div class="form-element">
                <label for="id_email">Email</label>
                <input type="email" name="email" maxlength="254" required="" id="id_email">
            </div>
            <div class="form-element">
                <label for="id_phone">Phone</label>
                <input type="text" name="phone" maxlength="14" required="" id="id_phone">
            </div>
        </div>
        <label for="id_desc">Description</label>
        <textarea name="desc" cols="40" rows="10" required="" id="id_desc"></textarea>
       
        {% csrf_token %}
        <button class="btn-full" type="submit">Create</button>
    </form>
</div>



{% endblock content %}
    

advertisingForum/ads/templates/detail.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="ad-box" id="detail">
        <div class="info-line">
            <div class="info-data">
                <p class="small-info"><ion-icon name="location-outline"></ion-icon>{{ad.adress}}</p> 
                <p class="small-info">
                    {% if ad.is_liked %}
                    <a href="{% url "like" ad.id %}"><ion-icon name="thumbs-up"></ion-icon></a>{{ad.total_likes}}
                    {% else %}
                    <a href="{% url "like" ad.id %}"><ion-icon name="thumbs-up-outline"></ion-icon></a>{{ad.total_likes}}
                    {% endif %}
                </p>
                   
            </div>
            <div class="info-data">
                <p class="small-info"><ion-icon name="call-outline"></ion-icon>{{ad.phone}}</p>
                <p class="small-info"><ion-icon name="mail-outline"></ion-icon>{{ad.email}}</p>
            </div>
        </div>
        <div class="main-box">
            <p class="industry">{{ad.display_industry}}</p>
            <h2>{{ad.company}}</h2>
            <div class="desc-row">
                <p><ion-icon name="document-text-outline"></ion-icon></p>
                <p>{{ad.desc}}</p>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

advertisingForum/ads/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="row"></div>

    <h2 class="form-title">Edit Advertisement</h2>
    {% if error %}
    <div class="alert alert-danger" role="alert">A simple danger alert—check it out!</div>
    {% endif %}
    <form class="create-form" action="{% url "edit" ad.id %}" method="POST">
        <div class="form-line">
            <div class="form-element">
                <label for="id company">Company</label>
                
                <input type="text" name="company" maxlength="300" required="" id="id_company" value="{{ad.company}}">
            </div>
            <div class="form-element">
                <label for="id-industry">industry</label>
                <select name="industry" required="" id="id_industry">
                    {% for id,industry in ad.industries %}
                    {% if not id %}
                    <option value="{{id}}" disabled>{{industry}}</option>
                    {% elif id == ad.industry %}
                    <option value="{{id}}" selected>{{industry}}</option>
                    {% else %}
                    <option value="{{id}}">{{industry}}</option>
                    {% endif %}

                    {% endfor %}

                </select>
            </div>
        </div>
        <div class="form-line">
            <div class="form-element long">
                <label for="id_address">Address</label>
                <input type="text" name="adress" maxlength="400" required="" id="id_adress" value="{{ad.adress}}">
            </div>
        </div>
        <div class="form-line">
            <div class="form-element">
                <label for="id_email">Email</label>
                <input type="email" name="email" maxlength="254" required="" id="id_email" value="{{ad.email}}">
            </div>
            <div class="form-element">
                <label for="id_phone">Phone</label>
                <input type="text" name="phone" maxlength="14" required="" id="id_phone" value="{{ad.phone}}">
            </div>
        </div>
        <label for="id_desc">Description</label>
        <textarea name="desc" cols="40" rows="10" required="" id="id_desc">{{ad.desc}}</textarea>
       
        {% csrf_token %}
        <button class="btn-full" type="submit">Edit</button>
    </form>
</div>



{% endblock content %}
    

advertisingForum/ads/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="ads-row">
        {% for ad in ads %}
        <div class="ad-col"></div>
            <a href="{% url "detail" ad.id %}">
                <div class ="ad-box">
                    <span>{{ad.display_industry}}</span>
                    <div class ="info-row">
                        <div class="info-col big">
                            <h2>{{ad.company}}</h2>
                            <p class="desc">{{ad.desc|truncatechars:100}}</p>
                            <p class="small-info"><ion-icon name="location-outline"></ion-icon>{{ad.adress}}</p>  

                        </div>
                    </div>
                    <div class="info-col">
                        <p class="small-info"><ion-icon name="call-outline"></ion-icon>{{ad.phone}}</p>
                        <p class="small-info"><ion-icon name="mail-outline"></ion-icon>{{ad.email}}</p>
                        <p class="small-info">
                            {% if ad.is_liked %}
                            <ion-icon name="thumbs-up"></ion-icon>{{ad.total_likes}}
                            
                            {% else %}
                            <ion-icon name="thumbs-up-outline"></ion-icon>{{ad.total_likes}}
                            {% endif %}
                            
                            
                        </p>
                    </div>
                </div>
            
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

advertisingForum/ads/templates/log.html
{% extends 'base.html' %}
{% block content %}
<div class="row thin">
    <h2 class="form-title">Log in</h2>
    {% if error %}
    <div class="alert alert-danger" role="alert">A simple danger alert—check it out!</div>
    {% endif %}
    <form class ="create-form" action="{% url "log" %}" method="POST">
        <label for="id_username">Username</label>
        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        <label for="id_password">Password</label>
        <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
        <p>Don't have an account?<a class="login-link" href="{% url "register" %}">Register</a></p>
        {% csrf_token %}
        <button class="btn-full" type="submit">Login</button>
    </form>
</div>
{% endblock content %}
 

advertisingForum/ads/templates/my.html
{% extends "base.html" %}
{% block content %}

<div class="row">
   <div class="ads-row">
      {% for ad in ads %}
      <div class="ad-col"></div>
         <a href="{% url "edit" ad.id %}">
            <div class ="ad-box">
               <span id="edit">Click to edit</span> 
               <span>{{ad.display_industry}}</span>
               <div class ="info-row">
                  <div class="info-col big">
                     <h2>{{ad.company}}</h2>
                     <p class="desc">{{ad.desc|truncatechars:100}}</p>
                     <p class="small-info"><ion-icon name="location-outline"></ion-icon>{{ad.adress}}</p>  

                  </div>
               </div>
               <div class="info-col">
                  <p class="small-info"><ion-icon name="call-outline"></ion-icon>{{ad.phone}}</p>
                  <p class="small-info"><ion-icon name="mail-outline"></ion-icon>{{ad.email}}</p>
                  <p class="small-info">
                     {% if ad.is_liked %}
                     <ion-icon name="thumbs-up"></ion-icon>{{ad.total_likes}}
                     
                     {% else %}
                     <ion-icon name="thumbs-up-outline"></ion-icon>{{ad.total_likes}}
                     {% endif %}
                  </p>
               </div>
            </div>
            
         </a>
      </div>
      {% endfor %}
   </div>
</div>

{% endblock content %}

advertisingForum/ads/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="row thin">
    <h2 class="form-title">Create account</h2>
    {% if error %}
    <div class="alert alert-danger" role="alert">{{error}}</div>
    {% endif %}
    
    <form class="create-form" action="{% url "register" %}" method="POST">
        <label for="id_username">Username</label>
        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
        <label for="id_password1">Password</label>
        <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
        <label for="id_password2">Confirm password</label>
        <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
        <p>Already have an account?<a class="login-link" href="{% url "log" %}">Log in</a></p>
        {% csrf_token %}
        <button class="btn-full" type="submit">Register</button>
    </form>

</div>


{% endblock content %}



<form action="{% url "register" %}" method="POST">
    <label for="id_username">Username</label>
    <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
    <label for="id_password1">Password</label>
    <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
    <label for="id_password2">Confirm password</label>
    <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
    {% csrf_token %}
    <button type="submit">Register</button>
</form>